version: "3"
services:
  proxy:
    restart: always
    ports:
      - 5000:80
    build:
      context: docker
      dockerfile: proxy.Dockerfile
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./application:/var/www/application
    depends_on:
      - application
  application:
    restart: always
    build:
      context: docker
      dockerfile: application.Dockerfile
    env_file:
      - config/xdebug.env
    volumes:
      - ./application:/var/www/application
      - ./config/php.ini:/usr/local/etc/php/php.ini:ro
    depends_on:
      - db
  db:
    restart: always
    ports:
      - 5432:5432
    build:
      context: docker
      dockerfile: db.Dockerfile
    env_file:
      - config/db.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./application:/var/www/application
  artisan:
    build:
      context: docker
      dockerfile: application.Dockerfile
    volumes:
      - ./application:/var/www/application
    entrypoint: ["php", "/var/www/application/artisan"]
